### PR TITLE
Visualisation updates

### PR DESCRIPTION
**Pull request by rnfinnegan**
vis updates and conduction system segmentation

### CODE REVIEW

**Comment by pchlap** [comment]
Hey @rnfinnegan , it looks like the tests are failing here... It seems to be the cardiac tests, an indexerror... I think you probably added something to the config which hasn't been added to the config in test_cardiac.py??

**Comment by pchlap** [comment]
> Hey @rnfinnegan , it looks like the tests are failing here... It seems to be the cardiac tests, an indexerror... I think you probably added something to the config which hasn't been added to the config in test_cardiac.py??

I could be wrong about this... I can't see any new fields in the config so not 100% whats happening here...

**Comment by rnfinnegan** [comment]
weird, I'm looking into this now

**Comment by rnfinnegan** [comment]
@pchlap got it sorted - I made some edits to the CARDIAC_DEFAULT_SETTINGS, the iteration staging was causing the index error

**Comment by pchlap** [comment]
> @pchlap got it sorted - I made some edits to the CARDIAC_DEFAULT_SETTINGS, the iteration staging was causing the index error

Awesome! Thanks :)

**Review by pchlap — APPROVED** [review]

**Pull request merged**
